//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedrivomatic.ButtonDriver.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class ButtonDriverConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static ButtonDriverConfiguration defaultInstance = ((ButtonDriverConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ButtonDriverConfiguration())));
        
        public static ButtonDriverConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SafetyBypass {
            get {
                return ((bool)(this["SafetyBypass"]));
            }
            set {
                this["SafetyBypass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double CommandTimeout {
            get {
                return ((double)(this["CommandTimeout"]));
            }
            set {
                this["CommandTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SettingsVersion {
            get {
                return ((int)(this["SettingsVersion"]));
            }
            set {
                this["SettingsVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<profiles currentProfile=\"Indoor\">\r\n  <p" +
            "rofile name=\"Indoor\" diagonalSpeedReduction=\"False\" nudgeDuration=\"1000\" xDurati" +
            "on=\"2000\" yDuration=\"2000\" CurrentSpeed=\"Slow\">\r\n    <speed name=\"Slow\" x=\"6\" yF" +
            "orward=\"9\" yBackward=\"9\" xDiag=\"14\" xDiagReduced=\"4\" yForwardDiag=\"6\" yForwardDi" +
            "agReduced=\"6\" yBackwardDiag=\"6\" yBackwardDiagReduced=\"0\" nudge=\"6\" />\r\n    <spee" +
            "d name=\"Walk\" x=\"10\" yForward=\"13\" yBackward=\"13\" xDiag=\"15\" xDiagReduced=\"5\" yF" +
            "orwardDiag=\"10\" yForwardDiagReduced=\"10\" yBackwardDiag=\"10\" yBackwardDiagReduced" +
            "=\"0\" nudge=\"6\" />\r\n    <speed name=\"Fast\" x=\"14\" yForward=\"17\" yBackward=\"17\" xD" +
            "iag=\"17\" xDiagReduced=\"7\" yForwardDiag=\"14\" yForwardDiagReduced=\"14\" yBackwardDi" +
            "ag=\"14\" yBackwardDiagReduced=\"0\" nudge=\"6\" />\r\n  </profile>\r\n  <profile name=\"Ou" +
            "tdoor\" diagonalSpeedReduction=\"False\" nudgeDuration=\"1000\" xDuration=\"2000\" yDur" +
            "ation=\"2000\" CurrentSpeed=\"Slow\">\r\n    <speed name=\"Slow\" x=\"6\" yForward=\"13\" yB" +
            "ackward=\"13\" xDiag=\"15\" xDiagReduced=\"5\" yForwardDiag=\"10\" yForwardDiagReduced=\"" +
            "10\" yBackwardDiag=\"10\" yBackwardDiagReduced=\"0\" nudge=\"6\" />\r\n    <speed name=\"W" +
            "alk\" x=\"10\" yForward=\"17\" yBackward=\"17\" xDiag=\"17\" xDiagReduced=\"7\" yForwardDia" +
            "g=\"14\" yForwardDiagReduced=\"14\" yBackwardDiag=\"14\" yBackwardDiagReduced=\"0\" nudg" +
            "e=\"6\" />\r\n    <speed name=\"Fast\" x=\"14\" yForward=\"21\" yBackward=\"21\" xDiag=\"22\" " +
            "xDiagReduced=\"12\" yForwardDiag=\"18\" yForwardDiagReduced=\"18\" yBackwardDiag=\"18\" " +
            "yBackwardDiagReduced=\"0\" nudge=\"6\" />\r\n  </profile>\r\n</profiles>")]
        public global::Eyedrivomatic.ButtonDriver.Configuration.ProfileCollection DrivingProfiles {
            get {
                return ((global::Eyedrivomatic.ButtonDriver.Configuration.ProfileCollection)(this["DrivingProfiles"]));
            }
            set {
                this["DrivingProfiles"] = value;
            }
        }
    }
}
