//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedrivomatic.Controls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DwellClickConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static DwellClickConfiguration defaultInstance = ((DwellClickConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DwellClickConfiguration())));
        
        public static DwellClickConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDwellClick {
            get {
                return ((bool)(this["EnableDwellClick"]));
            }
            set {
                this["EnableDwellClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00.2000000")]
        public global::System.TimeSpan DwellTime {
            get {
                return ((global::System.TimeSpan)(this["DwellTime"]));
            }
            set {
                this["DwellTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00.2000000")]
        public global::System.TimeSpan DwellTimeout {
            get {
                return ((global::System.TimeSpan)(this["DwellTimeout"]));
            }
            set {
                this["DwellTimeout"] = value;
            }
        }
    }
}
