//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedrivomatic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eyedrivomatic.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BrowsableList_Next {
            get {
                return ResourceManager.GetString("BrowsableList_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string BrowsableList_Prev {
            get {
                return ResourceManager.GetString("BrowsableList_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string CommandImage_Sleep {
            get {
                return ResourceManager.GetString("CommandImage_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        public static string CommandText_AddProfile {
            get {
                return ResourceManager.GetString("CommandText_AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Speed.
        /// </summary>
        public static string CommandText_AddProfileSpeed {
            get {
                return ResourceManager.GetString("CommandText_AddProfileSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Discover Device.
        /// </summary>
        public static string CommandText_AutoDiscover {
            get {
                return ResourceManager.GetString("CommandText_AutoDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommandText_Cancel {
            get {
                return ResourceManager.GetString("CommandText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string CommandText_Connect {
            get {
                return ResourceManager.GetString("CommandText_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string CommandText_Disconnect {
            get {
                return ResourceManager.GetString("CommandText_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string CommandText_NextDevice {
            get {
                return ResourceManager.GetString("CommandText_NextDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string CommandText_PrevDevice {
            get {
                return ResourceManager.GetString("CommandText_PrevDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommandText_Save {
            get {
                return ResourceManager.GetString("CommandText_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Relay {0} on-off..
        /// </summary>
        public static string CycleRelayMacroTask_DefaultNameFormat {
            get {
                return ResourceManager.GetString("CycleRelayMacroTask_DefaultNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle a relay. This changes the state of the relay off-&gt;on-&gt;off with a 200ms delay..
        /// </summary>
        public static string CycleRelayMacroTask_Description {
            get {
                return ResourceManager.GetString("CycleRelayMacroTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a value between 1 and {0}..
        /// </summary>
        public static string CycleRelayMacroTask_InvalidRelay {
            get {
                return ResourceManager.GetString("CycleRelayMacroTask_InvalidRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than 0..
        /// </summary>
        public static string CycleRelayMacroTask_InvalidRepeat {
            get {
                return ResourceManager.GetString("CycleRelayMacroTask_InvalidRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Relay {0}, repeat {1} times with a delay of {2} ms between repeats..
        /// </summary>
        public static string CycleRelayMacroTask_ToStringFormat {
            get {
                return ResourceManager.GetString("CycleRelayMacroTask_ToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay {0:0.00}s.
        /// </summary>
        public static string DelayTask_DefaultNameFormat {
            get {
                return ResourceManager.GetString("DelayTask_DefaultNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay must be greater than 0..
        /// </summary>
        public static string DelayTask_InvalidDelay {
            get {
                return ResourceManager.GetString("DelayTask_InvalidDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for {0:0.00} seconds..
        /// </summary>
        public static string DelayTask_ToStringFormat {
            get {
                return ResourceManager.GetString("DelayTask_ToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Understand and Agree.
        /// </summary>
        public static string Disclaimer_Button {
            get {
                return ResourceManager.GetString("Disclaimer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Eyedrivomatic System is potentially dangerous if used without proper caution. No member of the Eyedrivomatic team accept any responsibility whatsoever for any injuries to persons, or damage to property sustained during the use, or misuse of Eyedrivomatic. Use of The Eyedrivomatic System is entirely at the users own risk.
        ///To ensure safe operation, the following guidelines MUST be adhered to at all times;
        ///Users MUST be supervised at all times. The area of use MUST be entirely flat The area of use MUST b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Disclaimer_Text {
            get {
                return ResourceManager.GetString("Disclaimer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER.
        /// </summary>
        public static string Disclaimer_Title {
            get {
                return ResourceManager.GetString("Disclaimer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving.
        /// </summary>
        public static string DriveProfile_Default {
            get {
                return ResourceManager.GetString("DriveProfile_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal Speed
        ///Reduction Toggle.
        /// </summary>
        public static string DrivingView_DiagSpeedReduction {
            get {
                return ResourceManager.GetString("DrivingView_DiagSpeedReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Speeds.
        /// </summary>
        public static string DrivingView_DriveSpeeds {
            get {
                return ResourceManager.GetString("DrivingView_DriveSpeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward/Back Duration.
        /// </summary>
        public static string DrivingView_ForwardBackDuration {
            get {
                return ResourceManager.GetString("DrivingView_ForwardBackDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right Duration.
        /// </summary>
        public static string DrivingView_LeftRightDuration {
            get {
                return ResourceManager.GetString("DrivingView_LeftRightDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Nudge.
        /// </summary>
        public static string DrivingView_NudgeLeft {
            get {
                return ResourceManager.GetString("DrivingView_NudgeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Nudge.
        /// </summary>
        public static string DrivingView_NudgeRight {
            get {
                return ResourceManager.GetString("DrivingView_NudgeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string DrivingView_Speed_Fast {
            get {
                return ResourceManager.GetString("DrivingView_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANIC.
        /// </summary>
        public static string DrivingView_Speed_Manic {
            get {
                return ResourceManager.GetString("DrivingView_Speed_Manic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string DrivingView_Speed_Slow {
            get {
                return ResourceManager.GetString("DrivingView_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk.
        /// </summary>
        public static string DrivingView_Speed_Walk {
            get {
                return ResourceManager.GetString("DrivingView_Speed_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string DrivingView_Stop {
            get {
                return ResourceManager.GetString("DrivingView_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half.
        /// </summary>
        public static string DrivingView_XDuration_Half {
            get {
                return ResourceManager.GetString("DrivingView_XDuration_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half.
        /// </summary>
        public static string DrivingView_YDuration_Half {
            get {
                return ResourceManager.GetString("DrivingView_YDuration_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Hardware_DiagSpeedFullImage {
            get {
                return ResourceManager.GetString("Hardware_DiagSpeedFullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced.
        /// </summary>
        public static string Hardware_DiagSpeedReducedImage {
            get {
                return ResourceManager.GetString("Hardware_DiagSpeedReducedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        public static string Hardware_DirectionBackward {
            get {
                return ResourceManager.GetString("Hardware_DirectionBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward Left.
        /// </summary>
        public static string Hardware_DirectionBackwardLeft {
            get {
                return ResourceManager.GetString("Hardware_DirectionBackwardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward Right.
        /// </summary>
        public static string Hardware_DirectionBackwardRight {
            get {
                return ResourceManager.GetString("Hardware_DirectionBackwardRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Hardware_DirectionForward {
            get {
                return ResourceManager.GetString("Hardware_DirectionForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Left.
        /// </summary>
        public static string Hardware_DirectionForwardLeft {
            get {
                return ResourceManager.GetString("Hardware_DirectionForwardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Right.
        /// </summary>
        public static string Hardware_DirectionForwardRight {
            get {
                return ResourceManager.GetString("Hardware_DirectionForwardRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Hardware_DirectionLeft {
            get {
                return ResourceManager.GetString("Hardware_DirectionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Hardware_DirectionRight {
            get {
                return ResourceManager.GetString("Hardware_DirectionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Hardware_ReadyStateAnyImage {
            get {
                return ResourceManager.GetString("Hardware_ReadyStateAnyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Hardware_ReadyStateContinueImage {
            get {
                return ResourceManager.GetString("Hardware_ReadyStateContinueImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Hardware_ReadyStateResetImage {
            get {
                return ResourceManager.GetString("Hardware_ReadyStateResetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string Hardware_SafetyBypassSafeImage {
            get {
                return ResourceManager.GetString("Hardware_SafetyBypassSafeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkullAndCrossbones.
        /// </summary>
        public static string Hardware_SafetyBypassUnSafeImage {
            get {
                return ResourceManager.GetString("Hardware_SafetyBypassUnSafeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Name. The cannot be empty or only whitespace characters..
        /// </summary>
        public static string Macro_InvalidDisplayName {
            get {
                return ResourceManager.GetString("Macro_InvalidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MacrosImage_Power {
            get {
                return ResourceManager.GetString("MacrosImage_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt.
        /// </summary>
        public static string MacrosImage_Tilt {
            get {
                return ResourceManager.GetString("MacrosImage_Tilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string MacrosName_Mode {
            get {
                return ResourceManager.GetString("MacrosName_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string MacrosName_Power {
            get {
                return ResourceManager.GetString("MacrosName_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare.
        /// </summary>
        public static string MacrosName_Spare {
            get {
                return ResourceManager.GetString("MacrosName_Spare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Name. The cannot be empty or only whitespace characters..
        /// </summary>
        public static string MacroTask_InvalidDisplayName {
            get {
                return ResourceManager.GetString("MacroTask_InvalidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        public static string MillisecondsLong {
            get {
                return ResourceManager.GetString("MillisecondsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string MillisecondsShort {
            get {
                return ResourceManager.GetString("MillisecondsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string NewTaskViewModelName {
            get {
                return ResourceManager.GetString("NewTaskViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string ProfileName_Drive {
            get {
                return ResourceManager.GetString("ProfileName_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string ProfileSpeed_Default {
            get {
                return ResourceManager.GetString("ProfileSpeed_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X deflection when one of the nudge buttons are pressed while moving forward..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_Nudge {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_Nudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left or right deflection when one of the diagonal buttons are pressed..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_XDiag {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_XDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left or right deflection when one of the diagonal buttons are pressed while diagonal reduction is enabled..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_XDiagReduced {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_XDiagReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backward deflection when one of the forward diagonal buttons are pressed..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_YBackwardDiag {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_YBackwardDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backward deflection when one of the diagonal buttons are pressed while diagonal reduction is enabled..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_YBackwardDiagReduced {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_YBackwardDiagReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forward deflection when one of the forward diagonal buttons are pressed..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_YForwardDiag {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_YForwardDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forward deflection when one of the diagonal buttons are pressed while diagonal reduction is enabled..
        /// </summary>
        public static string SettingDescripion_ProfileSpeed_YForwardDiagReduced {
            get {
                return ResourceManager.GetString("SettingDescripion_ProfileSpeed_YForwardDiagReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forward deflection when the backward button is presssed..
        /// </summary>
        public static string SettingDescription_ProfileSpeed_Backward {
            get {
                return ResourceManager.GetString("SettingDescription_ProfileSpeed_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forward deflection when the forward button is presssed..
        /// </summary>
        public static string SettingDescription_ProfileSpeed_Forward {
            get {
                return ResourceManager.GetString("SettingDescription_ProfileSpeed_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the profile speed. This will be used to identify this speed to the user..
        /// </summary>
        public static string SettingDescription_ProfileSpeed_Name {
            get {
                return ResourceManager.GetString("SettingDescription_ProfileSpeed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X deflection when the right or left buttons are pressed..
        /// </summary>
        public static string SettingDescription_ProfileSpeed_X {
            get {
                return ResourceManager.GetString("SettingDescription_ProfileSpeed_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingGroupName_Appearance {
            get {
                return ResourceManager.GetString("SettingGroupName_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string SettingGroupName_DeviceConnection {
            get {
                return ResourceManager.GetString("SettingGroupName_DeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Settings.
        /// </summary>
        public static string SettingGroupName_DeviceSettings {
            get {
                return ResourceManager.GetString("SettingGroupName_DeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwell Click Settings.
        /// </summary>
        public static string SettingGroupName_DwellClick {
            get {
                return ResourceManager.GetString("SettingGroupName_DwellClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string SettingGroupName_ProfileSelection {
            get {
                return ResourceManager.GetString("SettingGroupName_ProfileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        public static string SettingGroupName_ProfileSettings {
            get {
                return ResourceManager.GetString("SettingGroupName_ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Connect at Startup.
        /// </summary>
        public static string SettingName_AutoConnect {
            get {
                return ResourceManager.GetString("SettingName_AutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingName_DwellClickEnabled {
            get {
                return ResourceManager.GetString("SettingName_DwellClickEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwell Repeat Delay.
        /// </summary>
        public static string SettingName_DwellClickRepeatDelay {
            get {
                return ResourceManager.GetString("SettingName_DwellClickRepeatDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwell Time.
        /// </summary>
        public static string SettingName_DwellClickTime {
            get {
                return ResourceManager.GetString("SettingName_DwellClickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwell Timeout.
        /// </summary>
        public static string SettingName_DwellClickTimeout {
            get {
                return ResourceManager.GetString("SettingName_DwellClickTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingName_ProfileName {
            get {
                return ResourceManager.GetString("SettingName_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward Deflection.
        /// </summary>
        public static string SettingName_ProfileSpeed_Backward {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Deflection.
        /// </summary>
        public static string SettingName_ProfileSpeed_Forward {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingName_ProfileSpeed_Name {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Deflection.
        /// </summary>
        public static string SettingName_ProfileSpeed_Nudge {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_Nudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right Deflection.
        /// </summary>
        public static string SettingName_ProfileSpeed_X {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right Diagonal Deflection (Normal).
        /// </summary>
        public static string SettingName_ProfileSpeed_XDiag {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_XDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right Diagonal Deflection (Reduced).
        /// </summary>
        public static string SettingName_ProfileSpeed_XDiagReduced {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_XDiagReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward Diagonal Deflection (Normal).
        /// </summary>
        public static string SettingName_ProfileSpeed_YBackwardDiag {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_YBackwardDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward Diagonal Deflection (Reduced).
        /// </summary>
        public static string SettingName_ProfileSpeed_YBackwardDiagReduced {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_YBackwardDiagReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Diagonal Deflection (Normal).
        /// </summary>
        public static string SettingName_ProfileSpeed_YForwardDiag {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_YForwardDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Diagonal Deflection (Reduced).
        /// </summary>
        public static string SettingName_ProfileSpeed_YForwardDiagReduced {
            get {
                return ResourceManager.GetString("SettingName_ProfileSpeed_YForwardDiagReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Bypass.
        /// </summary>
        public static string SettingName_SafetyBypass {
            get {
                return ResourceManager.GetString("SettingName_SafetyBypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingName_Theme {
            get {
                return ResourceManager.GetString("SettingName_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} seconds.
        /// </summary>
        public static string StatusView_DurationFormat {
            get {
                return ResourceManager.GetString("StatusView_DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Duration.
        /// </summary>
        public static string StatusView_NudgeDuration {
            get {
                return ResourceManager.GetString("StatusView_NudgeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Speed.
        /// </summary>
        public static string StatusView_NudgeSpeed {
            get {
                return ResourceManager.GetString("StatusView_NudgeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Bypass Status.
        /// </summary>
        public static string StatusView_SafetyBypassStatus {
            get {
                return ResourceManager.GetString("StatusView_SafetyBypassStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string StatusView_Seconds {
            get {
                return ResourceManager.GetString("StatusView_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°.
        /// </summary>
        public static string StatusView_ServoPositionFormat {
            get {
                return ResourceManager.GetString("StatusView_ServoPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string StatusView_Speed_Fast {
            get {
                return ResourceManager.GetString("StatusView_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANIC.
        /// </summary>
        public static string StatusView_Speed_Manic {
            get {
                return ResourceManager.GetString("StatusView_Speed_Manic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string StatusView_Speed_None {
            get {
                return ResourceManager.GetString("StatusView_Speed_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string StatusView_Speed_Slow {
            get {
                return ResourceManager.GetString("StatusView_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk.
        /// </summary>
        public static string StatusView_Speed_Walk {
            get {
                return ResourceManager.GetString("StatusView_Speed_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Servo Centere Point.
        /// </summary>
        public static string StatusView_XCenter {
            get {
                return ResourceManager.GetString("StatusView_XCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Servo.
        /// </summary>
        public static string StatusView_XServo {
            get {
                return ResourceManager.GetString("StatusView_XServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Servo Centere Point.
        /// </summary>
        public static string StatusView_YCenter {
            get {
                return ResourceManager.GetString("StatusView_YCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Servo.
        /// </summary>
        public static string StatusView_YServo {
            get {
                return ResourceManager.GetString("StatusView_YServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Duration.
        /// </summary>
        public static string TrimView_NudgeDuration {
            get {
                return ResourceManager.GetString("TrimView_NudgeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Speed.
        /// </summary>
        public static string TrimView_NudgeSpeed {
            get {
                return ResourceManager.GetString("TrimView_NudgeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string ViewName_Configuration {
            get {
                return ResourceManager.GetString("ViewName_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrainBox.
        /// </summary>
        public static string ViewName_DeviceConfig {
            get {
                return ResourceManager.GetString("ViewName_DeviceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyegaze.
        /// </summary>
        public static string ViewName_EyegazeConfig {
            get {
                return ResourceManager.GetString("ViewName_EyegazeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ViewName_GeneralConfiguration {
            get {
                return ResourceManager.GetString("ViewName_GeneralConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor Driving.
        /// </summary>
        public static string ViewName_IndoorDriving {
            get {
                return ResourceManager.GetString("ViewName_IndoorDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ViewName_Macros {
            get {
                return ResourceManager.GetString("ViewName_Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Actions.
        /// </summary>
        public static string ViewName_MacrosSettings {
            get {
                return ResourceManager.GetString("ViewName_MacrosSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string ViewName_ProfileConfig {
            get {
                return ResourceManager.GetString("ViewName_ProfileConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ViewName_Status {
            get {
                return ResourceManager.GetString("ViewName_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string ViewName_Trim {
            get {
                return ResourceManager.GetString("ViewName_Trim", resourceCulture);
            }
        }
    }
}
